module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('data', [
      {
        name: 'mobile',
        quantity: 2,
        distance: 230,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'pork',
        quantity: 34,
        distance: 250,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'socks',
        quantity: 6,
        distance: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'balls',
        quantity: 345,
        distance: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'TVs',
        quantity: 567,
        distance: 1024,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'appart',
        quantity: 32,
        distance: 478,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'helmet',
        quantity: 235,
        distance: 923400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'hair brush',
        quantity: 87,
        distance: 23786,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'chair',
        quantity: 125,
        distance: 1245,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'lamp',
        quantity: 3445,
        distance: 9074520,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'outlet',
        quantity: 837,
        distance: 1356,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'chocolate',
        quantity: 341575,
        distance: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'sandal',
        quantity: 34575,
        distance: 8454,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'balls',
        quantity: 345,
        distance: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'magnet',
        quantity: 7347,
        distance: 468,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'zipper',
        quantity: 1,
        distance: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'flowers',
        quantity: 4,
        distance: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'mop',
        quantity: 464,
        distance: 777,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'balls',
        quantity: 345,
        distance: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'plastic fork',
        quantity: 4457,
        distance: 7654,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'balls',
        quantity: 345,
        distance: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'greeting card',
        quantity: 556,
        distance: 234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'balls',
        quantity: 345,
        distance: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'toothbrush',
        quantity: 5534,
        distance: 4675,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'cup',
        quantity: 453,
        distance: 57534,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'boom box',
        quantity: 939,
        distance: 235,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'truck',
        quantity: 4646,
        distance: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'chapter book',
        quantity: 555,
        distance: 55900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'CD',
        quantity: 465,
        distance: 3467,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'sofa',
        quantity: 10000,
        distance: 10000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'credit card',
        quantity: 835,
        distance: 384,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
  },
};
